name: BuildRunner

on:
  push:
    branches:
      - dev
  pull_request:
    paths:
      - ".github/workflows/build_runner.yml"
      - "src/build_runner/**"
      # Ensure that the build runner checks get run when the minimum Zig version gets modified
      - "build.zig"
      - "build.zig.zon"
  workflow_dispatch:

jobs:
  check_build_runner:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        zig:
          - version: master
            build-runner-file: 0.14.0.zig
          # - version: 0.13.0
          #   build-runner-file: legacy.zig
          # - version: 0.12.0
          #   build-runner-file: legacy.zig
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig.version }}

      - name: Create temp zig project
        run: |
          mkdir $RUNNER_TEMP/TEMP_ZIG_PROJECT
          cd $RUNNER_TEMP/TEMP_ZIG_PROJECT
          zig init

      - name: Check build_runner builds
        run: |
          cd $RUNNER_TEMP/TEMP_ZIG_PROJECT
          zig build --build-runner ${{ github.workspace }}/src/build_runner/${{ matrix.zig.build-runner-file }}
